// Array of random acts of kindness
const kindnessActs = [
    "Compliment a stranger today.",
    "Donate clothes you no longer use.",
    "Leave a positive note for someone to find.",
    "Help a friend with their project.",
    "Buy a coffee for the person behind you in line.",
    "Offer to run an errand for a neighbor.",
    "Send a handwritten letter to a loved one.",
    "Pick up litter at a local park.",
    "Call a friend just to say hi.",
    "Bake cookies for your coworkers or neighbors.",
    "Give someone your seat on public transport.",
    "Volunteer at a local charity for a day.",
    "Surprise someone with a small gift.",
    "Smile and say hello to five new people today.",
    "Leave an encouraging comment on a social media post.",
    "Donate books to a library or a school.",
    "Give up your spot in line for someone in a rush.",
    "Pay for someone’s groceries anonymously.",
    "Offer to babysit for a busy parent.",
    "Bring in treats for your coworkers.",
    "Offer to help someone carry heavy bags.",
    "Send a thank-you note to someone who helped you.",
    "Clean up trash in your local area.",
    "Leave a generous tip at a restaurant.",
    "Pay for someone’s meal at a drive-thru.",
    "Help someone move or clean their home.",
    "Donate to a local food bank.",
    "Plant a tree or flowers in your neighborhood.",
    "Send flowers to a friend or family member.",
    "Offer to tutor someone for free.",
    "Run an errand for someone who can’t do it themselves.",
    "Leave an inspirational book in a public place.",
    "Bring extra umbrellas to share on a rainy day.",
    "Offer to do someone’s chores for a day.",
    "Leave a positive review for a small business.",
    "Help someone fix a flat tire.",
    "Donate blood at a local blood bank.",
    "Offer to wash someone’s car for free.",
    "Bring a meal to a new parent or someone recovering from illness.",
    "Send care packages to soldiers overseas.",
    "Write a positive recommendation for a coworker on LinkedIn.",
    "Let someone go ahead of you at a store checkout.",
    "Donate toys to a children’s hospital.",
    "Give away old electronics to someone in need.",
    "Help a senior with their shopping or errands.",
    "Pay for someone’s movie ticket.",
    "Offer free tutoring to students who need it.",
    "Cook a meal for a busy friend or family member.",
    "Send a thank-you card to your local fire or police department.",
    "Clean up after a public event.",
    "Donate used blankets to an animal shelter.",
    "Help a neighbor with yard work or gardening.",
    "Volunteer at a local community center.",
    "Leave a kind note on someone’s car windshield.",
    "Offer free professional advice to someone who needs it.",
    "Make a donation to a charity in someone else’s name.",
    "Buy extra groceries and donate them to a shelter.",
    "Host a clothing swap with friends or family.",
    "Pay for someone’s bus or train fare.",
    "Send homemade cookies to a neighbor.",
    "Help a friend or family member with their resume.",
    "Share an inspirational article or video with others.",
    "Offer to be a mentor to someone starting in your industry.",
    "Donate pet food to a local animal shelter.",
    "Leave a book in a public place with a note for someone to take it.",
    "Offer to help someone set up their tech devices.",
    "Help a neighbor with snow shoveling or leaf raking.",
    "Send a care package to someone going through a tough time.",
    "Volunteer to coach or assist with a kids’ sports team.",
    "Plant a community garden for everyone to enjoy.",
    "Help a coworker meet a deadline by offering your assistance.",
    "Organize a charity event or fundraiser for a cause you care about.",
    "Donate art supplies to a school or community center.",
    "Leave a box of free books in a public area.",
    "Surprise a coworker with coffee or breakfast.",
    "Send an anonymous gift to someone who’s struggling.",
    "Leave a reusable bag at the grocery store for someone to use.",
    "Help someone find a job or introduce them to useful contacts.",
    "Give your old bike to someone who needs transportation.",
    "Help a friend declutter their home.",
    "Write and share a blog post or social media post about kindness.",
    "Send a postcard to someone who loves to travel.",
    "Help an elderly person cross the street.",
    "Donate school supplies to a classroom in need.",
    "Send a care package to a college student during finals.",
    "Offer your photography skills to someone for free.",
    "Help a local business by recommending them to your friends.",
    "Set up a free library in your neighborhood.",
    "Offer to walk someone’s dog when they are busy.",
    "Make a charitable donation instead of buying holiday gifts.",
    "Help someone fix their computer or phone.",
    "Offer to mow a neighbor’s lawn when they are out of town.",
    "Donate shoes to a homeless shelter.",
    "Leave a bottle of water or snack for a delivery person.",
    "Offer to pick up groceries for someone who can’t go out.",
    "Donate old suitcases or bags to a homeless shelter.",
    "Offer to take photos at a friend’s special event for free.",
    "Help a friend or family member organize a big event.",
    "Share your favorite recipe with a friend and make it together.",
    "Host a kindness challenge with your friends or coworkers.",
    "Offer to run errands for a new parent or busy family.",
    "Give someone a ride to a doctor’s appointment.",
    "Organize a charity bake sale with your community.",
    "Bring water bottles to volunteers at a local event.",
    "Leave a kind review on a service provider’s website.",
    "Help a student with their homework or college applications.",
    "Offer to babysit for free so parents can have a night out.",
    "Send a book to a prisoner or someone in need of reading material.",
    "Create care packages for homeless people and distribute them.",
    "Help a local charity with their social media accounts.",
    "Organize a charity walk or run for a cause you support.",
    "Offer to house-sit or pet-sit for someone on vacation.",
    "Host a neighborhood cleanup day.",
    "Create handmade cards for people in nursing homes or hospitals.",
    "Donate hair to a charity that makes wigs for cancer patients.",
    "Bring treats to a local school or daycare center.",
    "Leave a coupon or gift card on someone’s windshield.",
    "Offer to help someone move into a new home.",
    "Donate your time to help at a local shelter or soup kitchen.",
    "Make blankets or scarves for people in need during winter.",
    "Create a DIY project with a child or young person.",
    "Help a nonprofit organization with their website or design work.",
    "Give a motivational speech to a group of students or peers.",
    "Support a friend’s small business by sharing their services.",
    "Donate gently used baby clothes to a new parent in need.",
    "Send surprise flowers or chocolates to someone at work.",
    "Write down positive affirmations and leave them in public places.",
    "Teach a child or a friend how to ride a bike.",
    "Bring reusable bags to a local grocery store and share them.",
    "Host a community yard sale and donate the proceeds to charity.",
    "Surprise a family member with breakfast in bed.",
    "Leave quarters at a laundromat for people who need them.",
    "Make a meal for someone who is going through a hard time.",
    "Take a coworker out for coffee to show appreciation.",
    "Organize a kindness scavenger hunt in your community.",
    "Start a positivity chain on social media.",
    "Donate unused toiletries to a shelter or community center.",
    "Bring flowers to someone’s office or workplace to brighten their day.",
    "Organize a neighborhood potluck to bring people together.",
    "Leave a small gift on a coworker’s desk anonymously.",
    "Help someone research and apply for a new job opportunity.",
    "Host a free garage sale where everything is free for the community.",
    "Leave dog treats at a local dog park for pet owners.",
    "Buy someone a reusable water bottle to encourage eco-friendliness.",
    "Pay for someone’s parking meter or ticket.",
    "Write a kind note to your barista or server.",
    "Bring groceries to a neighbor in need.",
    "Offer to help someone assemble furniture.",
    "Set up a kindness board at work or school for people to share positive messages.",
    "Offer to walk someone’s dog when they are away.",
    "Donate gift cards to a local shelter or charity."
    // Add more acts of kindness to fill the array up to 1000 as needed
];

// This array can be used in your JavaScript generator!
// Function to generate and display a random act of kindness
function generateKindness() {
    // Get a random index from the kindnessActs array
    const randomIndex = Math.floor(Math.random() * kindnessActs.length);
    
    // Get the DOM element to display the random act
    const kindnessElement = document.getElementById('kindnessAct');
    
    // Apply fade-out animation before changing content
    kindnessElement.classList.remove('fade-in');
    
    // Trigger a reflow to reset the animation (ensures smooth transition)
    void kindnessElement.offsetWidth;
    
    // Change the content to the randomly selected kindness act
    kindnessElement.innerHTML = kindnessActs[randomIndex];
    
    // Apply the fade-in animation to the updated content
    kindnessElement.classList.add('fade-in');
}

// Optional: Add event listener to button (for better separation of concerns)
document.querySelector('button').addEventListener('click', generateKindness);
